### PR TITLE
bump to 1.0.1

### PR DESCRIPTION
**Pull request by scpeters**
Make a patch release of `ign-citadel` since it's tagged release still has references to bitbucket in the yaml file:

* https://github.com/ignitionrobotics/ign-citadel/compare/ignition-citadel_1.0.0...main

I'd like to test https://github.com/ignition-tooling/release-tools/pull/313 with this release.

### CODE REVIEW

**Review by j-rivero — APPROVED** [review]

**Comment by chapulina** [comment]
Can we include https://github.com/ignitionrobotics/ign-citadel/pull/4?

**Comment by chapulina** [comment]
`-release` updates too: https://github.com/ignition-release/ign-citadel-release/pull/1

**Comment by scpeters** [comment]
> Can we include #4?

yes, I'm testing it now

**Comment by scpeters** [comment]
> > Can we include #4?
> 
> yes, I'm testing it now

merged

**Review by chapulina — APPROVED** [review]

**Pull request merged**
